---
# GH is still on minima 2.5.1, auto comes in the unreleased 3.0
remote_theme: jekyll/minima
minima:
  skin: auto
  social_links:
    - platform: mastodon
      user_url: "https://jasette.facil.services/@dermoth"
    - platform: stackoverflow
      user_url: "https://stackoverflow.com/users/969196/thomas-guyot-sionnest"
    - platform: linkedin
      user_url: "https://www.linkedin.com/in/tguyot/"
